services:
  app:
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    env_file:
      - .env.dev
      - .env
    environment:
      - GIT_EDITOR=code --wait
      - RELEASE_NODE=app-node-1@app.exins
    image: elixir:1.18

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    volumes:
      - ..:/workspace:cached
      - app:/workspace/volumes/app:cached
      - postgres-data:/workspace/volumes/postgres-data
      - type: volume
        source: app
        target: /workspace/livebook
        volume:
          subpath: livebook
      - type: volume
        source: app
        target: /workspace/exins/priv
        volume:
          subpath: exins/priv

  db:
    env_file:
      - .env.dev
      - .env
    hostname: host.exins
    image: postgres:18
    # network_mode: service:app
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/18/data
        volume:
          subpath: 18/data

  pgAdmin:
    env_file:
      - .env.dev
      - .env
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_LISTEN_PORT:-5050}:80"
    restart: unless-stopped
    volumes:
      - type: volume
        source: app
        target: /pgadmin4/config_local.py
        volume:
          subpath: pgadmin4/config_local.py

  livebook:
    env_file:
      - .env.dev
      - .env
    environment:
      - LIVEBOOK_DEFAULT_RUNTIME=attached:app-node-1@host.exins:${RELEASE_COOKIE}
      - LIVEBOOK_DISTRIBUTION=exins
    image: ghcr.io/livebook-dev/livebook
    network_mode: service:db
    restart: unless-stopped 
    volumes:
      - type: volume
        source: app
        target: /data
        volume:
          subpath: livebook
volumes:
  app:
  postgres-data: