services:
  app:
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    image: elixir:1.18

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    volumes:
      - ..:/workspace:cached

  db:
        environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exins_dev
hostname: host.exins
    image: postgres:17
# network_mode: service:app
    restart: unless-stopped
    volumes:
      - postgres-data-2:/var/lib/postgresql/data

  livebook:
    environment:
      - LIVEBOOK_PASSWORD="new passwordW@!"
    image: ghcr.io/livebook-dev/livebook
    network_mode: service:db
    restart: unless-stopped 
    volumes:
      - ..:/data:cached
volumes:
  postgres-data-2:
