defmodule Exins.PolicySystem.PolicyDocument do
  use Ash.Resource,
  domain: Exins.PolicySystem,
  data_layer: :embedded

  @doc """
  Represents a detailed policy document.
  """
  def default_term, do: 365

  actions do
    defaults [:create, :read, :update, :destroy]
  end

  attributes do
    # Autogenerated UUID primary key called `:id`
    uuid_primary_key :id do
      description "The system generated unique id for the policy record"
    end

    attribute :policy_number, :ci_string do
      description "The policy number."
      allow_nil? false
    end

    attribute :status, :atom do
      description "The status of the policy"
      constraints [one_of: [:quote, :in_force, :cancelled]]
      default :quote
      allow_nil? false
    end

    attribute :inception_date, :date do
      description "The effective date of the policy term"
      default &Date.utc_today/0
    end

    attribute :expiry_date, :date do
      description "The expiry date of the policy term"
      default fn changeset ->
        inception_date = changeset.data.inception_date
        Date.add(inception_date, default_term()) # Add the default policy term to calculate the expiry date.
      end
    end

    # attribute :total_premium, :decimal

    attribute :loading, :decimal do
      description "The loading percentage (e.g., 10%)"
      constraints [
        min: 0,
        max: 1
      ]
      default 1
    end

    attribute :discount, :decimal do
      description "The discount percentage (e.g., 5%)."
      constraints [
        min: 0,
        max: 1
      ]
      default 0
    end

    # Embedded resource: Coverage
    attribute :coverages, {:array, Exins.PolicySystem.PolicyCoverage}
  end

  calculations do

  end

  code_interface do
    define_for ExIns.PolicySystem
    define :create, action: :create
    define :read_all, action: :read
    define :update, action: :update
    define :destroy, action: :destroy
  end

end
