defmodule ExIns.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :policy_number, :text
      add :status, :text, null: false, default: "quote"
    end
  end

  def down do
    drop table(:policies)
  end
end
