defmodule ExIns.Repo.Migrations.AddEmbeddedPolicyResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:policies) do
      remove :status
      remove :policy_number

      add :doc, :map
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:policies) do
      remove :updated_at
      remove :created_at
      remove :doc

      add :policy_number, :text
      add :status, :text, null: false, default: "quote"
    end
  end
end
